# Generated by Django 4.2.30 on 2026-07-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('preferred_location', models.CharField(max_length=200)),
                ('property_ref', models.CharField(blank=True, default='', max_length=200)),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Visit Lead',
                'verbose_name_plural': 'Site Visit Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
