# Generated by Django 4.2.30 on 2026-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('property_type', models.CharField(choices=[('plot', 'Plot'), ('rental', 'Rental'), ('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20)),
                ('sector_location', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('expected_price', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('valued', 'Valued'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seller Submission',
                'verbose_name_plural': 'Seller Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
