# Generated by Django 4.2.30 on 2026-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_sellersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitlead',
            name='preferred_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
