# Generated by Django 4.2.30 on 2026-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_sitevisitlead_preferred_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitlead',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10),
        ),
    ]
