# Generated by Django 4.2.30 on 2026-07-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name — e.g. 'Suncity Rohtak' or 'Omaxe City'.", max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Official layout / sector map image. High-res PNG or JPG.', upload_to='sector_maps/')),
                ('description', models.TextField(blank=True, help_text='Optional context — sector, developer, plot count, etc.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sector Map',
                'verbose_name_plural': 'Sector Maps',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Decimal latitude, e.g. 28.862345 for a Rohtak property.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Decimal longitude, e.g. 76.587210 for a Rohtak property.', max_digits=9, null=True),
        ),
    ]
