# Generated by Django 4.2.30 on 2026-07-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_sectormap_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('plot', 'Plot'), ('villa', 'Villa'), ('flat', 'Flat / Apartment'), ('builder_floor', 'Builder Floor'), ('commercial', 'Commercial'), ('farmhouse', 'Farmhouse')], default='flat', help_text='Category shown on listing cards and filters.', max_length=20),
        ),
    ]
